language: node_js
node_js:
- 0.1
deploy:
  provider: releases
  api_key:
    secure: S2JVfYhWj4b2DvjsPtJYqUrAUtC9Mwdc1kMkA+p/LeSYJOZL8gFq55YReAPI1pNKSTJxwnxdlbMb5gtxyItVj7vz23Inv5S1DwialwgTff3ZV1JOquT91BeHnvphjBdm5L8G65QI35xEu5d1AuFr+cv6q+ocGr/k70b56fnEPcs=
  file: "product/le.min.js"
  skip_cleanup: true
  on:
    repo: logentries/le_js
    tags: true
  - 0.10
env:
  - secure: "RHRZZTijhsDbuoJaNDPnLs3ipE4LjackSNe5wBiycD4YL5cAuE+smX1Wdee3VYf25q5SaBI42/V+nb4vtBiJLU5vTnriij0vsckvlIyj5vY4Rf/uLSJ2VfIw4/Uo1K45mqnZLgTqKrKVVTHU0Irl20d34pQeb51jGDx6DCwuYmY="
  - secure: "HPKeHnTPNAItQjjNlgIhrKwnLaVpz5kcSXISu72s1lu8+VoZL4cYhjqB5zMPqAMMroCYsXF75570wOCzFcJAckS0BpSNKaYtazXvyZDQymGmAqI7RxsNEx++b/fW3RRBbw7uA8LT0hoA0k1BV99TYW0xXJ7/v3PmcugeC0jCGuo="
